### PR TITLE
v1.3, FVTT v10 migration and Item Support

### PR DESCRIPTION
**Pull request by Geekswordsman**
Updated system.json for a v1.3 launch.
Migrated data to Foundry v10.
Added support for Items.
Redesigned the Actor sheet to support Items.
Removed support for older versions of Foundry, supporting only v10 from this point on.

### CODE REVIEW

**Comment by jbhaywood** [comment]
Just curious about the motivation for adding items, since the original game doesn't have any rules around them.

**Comment by jbhaywood** [comment]
Looks like there are a couple issues with getting two hats.
1) The Hat 2 option renders over the Items panel.
2) The Hat 2 roller button doesn't do anything.

Can you get those fixed? Here's a screenshot of the rendering issue...
image

Thanks!

**Comment by Geekswordsman** [comment]
> Just curious about the motivation for adding items, since the original game doesn't have any rules around them.

If you have the patreon, there are sample items that you included as extras that you can give to the players to shake things up.  This is mentioned, and utilized, in Critical Role's play of Honey Heist - "Trinket's Honey Heist".  In it, they give out glasses that let a bear see through the immediate walls around them, a bamboo spoon that can turn into a full on tree (and back again), special honey that if they eat it, they can teleport to another place they nearby that has some of the same honey, and a trenchcoat that allows two bears to appear as one bear wearing a trenchcoat.

Aside from the special items, it would be nice to have a place to mark down anything the bears do happen to find along the way.  Be it pots of honey, key cards, passwords, notes, or anything else of note.

**Comment by Geekswordsman** [comment]
Updated the styling now to fix the issue when 2 hats are available; which also fixes the roller for hat #2 not functioning!

**Pull request merged**
